import Head from 'next/head';

import styles from '../styles/Home.module.css';
import HomePage from './HomePage';

const Home = () => {
  return (
    <>
      <Head>
        <title>Relipa Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <HomePage />
      </main>
    </>
  );
};

export default Home;
